<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookstore [
    <!ELEMENT bookstore (book+)>
    <!ELEMENT book (title, author, price)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT price (#PCDATA)>

    <!ATTLIST title type CDATA>
]>
<bookstore>
    <book>
        <title type="biography">Foundation</title>
        <author>Isaac Asimov</author>
        <price>3000</price>
    </book> 
</bookstore>


